name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - yaml
  - pip:
      - jaal
      - networkx
      - LeOpardLink==0.1.3.1
      - threading
      - base64
      - time
      - socket
